CREATE TABLE Workout(
	Id UNIQUEIDENTIFIER  NOT NULL DEFAULT NEWSEQUENTIALID(),
	Title NVARCHAR(300) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	Privacy SMALLINT NOT NULL DEFAULT 0,
	Price FLOAT NOT NULL DEFAULT 0,
	CONSTRAINT pk_workout PRIMARY KEY (Id)
)

CREATE TABLE Section(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	WorkoutId UNIQUEIDENTIFIER NOT NULL,
	Title NVARCHAR(300) NOT NULL,
	SectionType SMALLINT NOT NULL DEFAULT 0,
	Repeats SMALLINT NULL,
	Duration TIME NULL,
	Rest TIME NULL,
	CONSTRAINT pk_section PRIMARY KEY (Id),
	CONSTRAINT fk_section_workout FOREIGN KEY (WorkoutId) REFERENCES Workout(Id)
)

CREATE TABLE SectionExercise(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	SectionId  UNIQUEIDENTIFIER NOT NULL,
	ExerciseId INT NOT NULL,
	Sets SMALLINT NOT NULL DEFAULT 1,
	CompletionDistance FLOAT NULL,
	CompletionDuration TIME NULL,
	CompletionRepetitions SMALLINT NULL,
	Rest TIME NULL,
	RestAsNeeded BIT NOT NULL DEFAULT 0,
	CONSTRAINT pk_sectionexercise PRIMARY KEY (Id),
	CONSTRAINT fk_sectionexercise_section FOREIGN KEY (sectionId) REFERENCES Section(Id)
)